# Generated by Django 3.0.4 on 2020-04-06 11:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ask_bolgova', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='like',
            unique_together=set(),
        ),
    ]
