# Generated by Django 3.0.4 on 2020-04-05 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ask_bolgova', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='like',
            name='vote',
            field=models.SmallIntegerField(choices=[(-1, 'Не нравится'), (1, 'Нравится')], default=0),
        ),
    ]
