# Generated by Django 3.0.4 on 2020-04-05 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ask_bolgova', '0002_auto_20200405_1934'),
    ]

    operations = [
        migrations.AlterField(
            model_name='like',
            name='vote',
            field=models.SmallIntegerField(choices=[(-1, 'Не нравится'), (1, 'Нравится')]),
        ),
    ]
