# Generated by Django 3.0.4 on 2020-04-07 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ask_bolgova', '0002_auto_20200406_1446'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='avatar',
            field=models.ImageField(blank=True, default='settings.STATIC_URL/img/avatars/avatar.png', upload_to=''),
        ),
    ]
