# Generated by Django 3.0.4 on 2020-04-05 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ask_bolgova', '0003_auto_20200405_2048'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='rating',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterUniqueTogether(
            name='like',
            unique_together={('user', 'object_id')},
        ),
    ]
