# Generated by Django 3.0.4 on 2020-04-07 18:11

import django.core.files.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ask_bolgova', '0003_auto_20200407_2107'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='avatar',
            field=models.ImageField(blank=True, default='settings.STATIC_URL/img/avatars/avatar.png', storage=django.core.files.storage.FileSystemStorage(location='/static/'), upload_to=''),
        ),
    ]
