# Generated by Django 3.0.4 on 2020-05-19 13:22

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ask_bolgova', '0011_auto_20200407_2127'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='avatar',
            field=models.ImageField(blank=True, upload_to='uploads/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=('jpeg', 'jpg', 'png'))]),
        ),
        migrations.AlterField(
            model_name='tag',
            name='title',
            field=models.CharField(db_index=True, max_length=30, unique=True),
        ),
    ]
