# Generated by Django 3.0.4 on 2020-05-20 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ask_bolgova', '0013_auto_20200519_1734'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='id_answer',
            field=models.IntegerField(default=None),
        ),
    ]
