# Generated by Django 3.0.4 on 2020-05-20 12:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ask_bolgova', '0017_auto_20200520_1533'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='id_answer',
        ),
    ]
