# Generated by Django 3.0.4 on 2020-05-20 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ask_bolgova', '0018_remove_question_id_answer'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='id_answer',
            field=models.IntegerField(default=-1),
        ),
    ]
